import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import ImageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Character, getCharacterResults } from "../types";

export const getStaticProps: GetServerSideProps = async (ctx) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: getCharacterResults = await res.json();
  return {
    props: {
      characters: results,
    },
  };
};

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* DB CONNECT: {process.env.NEXT_PUBLIC_DB_CONNECT}
      <hr/> */}
      {characters.map((character) => {
        return (
          <div key={character.id}>
            <Link href={`/characters/${character.id}`}>
              <a>
                <h3>{character.name}</h3>
              </a>
            </Link>
            <Image
              loader={ImageLoader}
              unoptimized
              src={character.image}
              alt={character.name}
              width="200"
              height="200"
            />
          </div>
        );
      })}
    </div>
  );
};

export default Home;
